### ISSUE TITLE
tens add demo

### ISSUE THREAD

**Issue by desenmeng** [desenmeng/tens#3]

**Comment by desenmeng** [comment]
https://www.tensorflow.org/extend/language_bindings

**Comment by desenmeng** [comment]
![image](https://user-images.githubusercontent.com/1209159/28177244-c83c8b38-682c-11e7-8e62-185d8d9ce42a.png)

**Comment by demohi** [comment]
@EricPoker  目前来看，c api 支持的功能非常有限

**Comment by desenmeng** [comment]
https://github.com/tensjs/tens/commit/81738fe60c8bff1eac5476c90086aba86f405a6f

**Comment by desenmeng** [comment]
https://github.com/tensorflow/tensorflow/issues/10089
